package webview2

type COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT uint32

const (
	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_PNG  COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT = 0
	COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT_JPEG COREWEBVIEW2_CAPTURE_PREVIEW_IMAGE_FORMAT = 1
)

type COREWEBVIEW2_SCRIPT_DIALOG_KIND uint32

const (
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT        COREWEBVIEW2_SCRIPT_DIALOG_KIND = 0
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM      COREWEBVIEW2_SCRIPT_DIALOG_KIND = 1
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT       COREWEBVIEW2_SCRIPT_DIALOG_KIND = 2
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD COREWEBVIEW2_SCRIPT_DIALOG_KIND = 3
)

type COREWEBVIEW2_PROCESS_FAILED_KIND uint32

const (
	COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED      COREWEBVIEW2_PROCESS_FAILED_KIND = 0
	COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED       COREWEBVIEW2_PROCESS_FAILED_KIND = 1
	COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE COREWEBVIEW2_PROCESS_FAILED_KIND = 2
)

type COREWEBVIEW2_PERMISSION_KIND uint32

const (
	COREWEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION COREWEBVIEW2_PERMISSION_KIND = 0
	COREWEBVIEW2_PERMISSION_KIND_MICROPHONE         COREWEBVIEW2_PERMISSION_KIND = 1
	COREWEBVIEW2_PERMISSION_KIND_CAMERA             COREWEBVIEW2_PERMISSION_KIND = 2
	COREWEBVIEW2_PERMISSION_KIND_GEOLOCATION        COREWEBVIEW2_PERMISSION_KIND = 3
	COREWEBVIEW2_PERMISSION_KIND_NOTIFICATIONS      COREWEBVIEW2_PERMISSION_KIND = 4
	COREWEBVIEW2_PERMISSION_KIND_OTHER_SENSORS      COREWEBVIEW2_PERMISSION_KIND = 5
	COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ     COREWEBVIEW2_PERMISSION_KIND = 6
)

type COREWEBVIEW2_PERMISSION_STATE uint32

const (
	COREWEBVIEW2_PERMISSION_STATE_DEFAULT COREWEBVIEW2_PERMISSION_STATE = 0
	COREWEBVIEW2_PERMISSION_STATE_ALLOW   COREWEBVIEW2_PERMISSION_STATE = 1
	COREWEBVIEW2_PERMISSION_STATE_DENY    COREWEBVIEW2_PERMISSION_STATE = 2
)

type COREWEBVIEW2_WEB_ERROR_STATUS uint32

const (
	COREWEBVIEW2_WEB_ERROR_STATUS_UNKNOWN                              COREWEBVIEW2_WEB_ERROR_STATUS = 0
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT COREWEBVIEW2_WEB_ERROR_STATUS = 1
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED                  COREWEBVIEW2_WEB_ERROR_STATUS = 2
	COREWEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS   COREWEBVIEW2_WEB_ERROR_STATUS = 3
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED                  COREWEBVIEW2_WEB_ERROR_STATUS = 4
	COREWEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID               COREWEBVIEW2_WEB_ERROR_STATUS = 5
	COREWEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE                   COREWEBVIEW2_WEB_ERROR_STATUS = 6
	COREWEBVIEW2_WEB_ERROR_STATUS_TIMEOUT                              COREWEBVIEW2_WEB_ERROR_STATUS = 7
	COREWEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE   COREWEBVIEW2_WEB_ERROR_STATUS = 8
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED                   COREWEBVIEW2_WEB_ERROR_STATUS = 9
	COREWEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET                     COREWEBVIEW2_WEB_ERROR_STATUS = 10
	COREWEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED                         COREWEBVIEW2_WEB_ERROR_STATUS = 11
	COREWEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT                       COREWEBVIEW2_WEB_ERROR_STATUS = 12
	COREWEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED               COREWEBVIEW2_WEB_ERROR_STATUS = 13
	COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED                   COREWEBVIEW2_WEB_ERROR_STATUS = 14
	COREWEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED                      COREWEBVIEW2_WEB_ERROR_STATUS = 15
	COREWEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR                     COREWEBVIEW2_WEB_ERROR_STATUS = 16
)

type COREWEBVIEW2_WEB_RESOURCE_CONTEXT uint32

const (
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL                  COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 0
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT             COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 1
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET           COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 2
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE                COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 3
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA                COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 4
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FONT                 COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 5
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT               COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 6
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST     COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 7
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH                COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 8
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK           COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 9
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE         COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 10
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET            COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 11
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST             COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 12
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE      COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 13
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_PING                 COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 14
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 15
	COREWEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER                COREWEBVIEW2_WEB_RESOURCE_CONTEXT = 16
)

type COREWEBVIEW2_MOVE_FOCUS_REASON uint32

const (
	COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC COREWEBVIEW2_MOVE_FOCUS_REASON = 0
	COREWEBVIEW2_MOVE_FOCUS_REASON_NEXT         COREWEBVIEW2_MOVE_FOCUS_REASON = 1
	COREWEBVIEW2_MOVE_FOCUS_REASON_PREVIOUS     COREWEBVIEW2_MOVE_FOCUS_REASON = 2
)

type COREWEBVIEW2_KEY_EVENT_KIND uint32

const (
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN        COREWEBVIEW2_KEY_EVENT_KIND = 0
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP          COREWEBVIEW2_KEY_EVENT_KIND = 1
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN COREWEBVIEW2_KEY_EVENT_KIND = 2
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP   COREWEBVIEW2_KEY_EVENT_KIND = 3
)
