package webview2

type _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerVtbl struct {
	_IUnknownVtbl
	Invoke ComProc
}

type ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler struct {
	vtbl *_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerVtbl
	impl _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerImpl
}

func _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerIUnknownQueryInterface(this *ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler, refiid, object uintptr) uintptr {
	return this.impl.QueryInterface(refiid, object)
}

func _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerIUnknownAddRef(this *ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler) uintptr {
	return this.impl.AddRef()
}

func _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerIUnknownRelease(this *ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler) uintptr {
	return this.impl.Release()
}
func _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerInvoke(this *ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler, errorCode uintptr, id *uint16) uintptr {
	return this.impl.AddScriptToExecuteOnDocumentCreatedCompleted(errorCode, id)
}

type _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerImpl interface {
	_IUnknownImpl
	AddScriptToExecuteOnDocumentCreatedCompleted(errorCode uintptr, id *uint16) uintptr
}

var _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerFn = _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerVtbl{
	_IUnknownVtbl{
		NewComProc(_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerIUnknownQueryInterface),
		NewComProc(_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerIUnknownAddRef),
		NewComProc(_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerIUnknownRelease),
	},
	NewComProc(_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerInvoke),
}

func NewICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler(impl _ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerImpl) *ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler {
	return &ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandler{
		vtbl: &_ICoreWebView2AddScriptToExecuteOnDocumentCreatedCompletedHandlerFn,
		impl: impl,
	}
}
