package webview2

type _ICoreWebView2DevToolsProtocolEventReceivedEventArgsVtbl struct {
	_IUnknownVtbl
	GetParameterObjectAsJson ComProc
}

type ICoreWebView2DevToolsProtocolEventReceivedEventArgs struct {
	vtbl *_ICoreWebView2DevToolsProtocolEventReceivedEventArgsVtbl
}
